### ISSUE TITLE
Transfering this repository.

### ISSUE THREAD

**Issue by dantleech** [psiphp/content-type#18]
Just so this doesn't come as a suprise to anybody, I am going to transfer this repository to https://github.com/psiphp where I will continue to develop it as explained in the mailing list emails. I consider this to be fine as I am the only contributor to this component.

**Comment by dbu** [comment]
as the repo is very new, and has no stars / forks yet, i expect it to not be used by people yet. i am ok with moving it.

**Comment by dantleech** [comment]
also it goes without saying that everyone is *more* than welcome to help with it (same goes for the other org in general).
